version: '3.9'

services:
  postgres:
    image: postgres:13-alpine
    container_name: database
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - TZ=Asia/Bangkok
    ports:
      - ${DB_PORT}:5432
    volumes:
      - data:/var/lib/postgresql/data
volumes:
  data:
